### ISSUE TITLE
Scraper for collecting neutral dataset is needed

### ISSUE THREAD

**Issue by AlexDel** [AlexDel/levheimcube#8]
For our project we need a collection of paragraphs that represent neutral text.
The best source so far is Russian Wikipedia.

The task is the following:
- Take a random wikipedia article from Russian Wiki via REST API. GET request is - `https://ru.wikipedia.org/api/rest_v1/page/random/html`. It comes in html form. Use `requests` library for that [https://2.python-requests.org/en/master/](https://2.python-requests.org/en/master/)
- Take all paragraphs from it (all nodes with `<p>` tags). Use `BeuatifullSoup` for this. This may be  [relevant example ](https://www.dataquest.io/blog/web-scraping-tutorial-python/). 

Scraper should be placed in 'data' directory. It should be class or function that takes an number of request arguemnt (a number of random pages we want to fetch), collect all paragraphs from all articles and push them to csv. Each row in csv is a paragraph. Paragraphs that are longer than 3000 symbols should be omitted.

After each article iteration there should be a pause of 1 second (use `time.sleep' module)

**Comment by LiubovVdovina** [comment]
Issue is solved
commit: 24a802403a8df66af988cc0a3d032fa42d177106
